name : CI

on :
  push:
    branches: [ master ]
  pull_request :
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - uses:
      - name:
        uses:
        with:
          java-version: 11
      - name: Build with Gradle
        run : ./gradle build

